### PR TITLE
oclifify

### PR DESCRIPTION
**Pull request by jdxcode**

### CODE REVIEW

**Comment by raulb** [comment]
@jdxcode Tell me more! I'm all👂

**Comment by jdxcode** [comment]
a couple changes here, first we're getting rid of the internal caching by dropping in an `.oclif.manifest.json` file that is basically the same thing. This way our customer's clients don't have to cache the plugins and they're really fast. In total, by adding this functionality the overhead of the core has gone down from ~400ms to ~190ms, so it's a noticeable speed improvement.

The other change is we're using a new scope convention and renaming all the core plugins to match. It doesn't really do anything for core plugins except make them easier to find, but for non-core plugins they'll have shorthand installs. So if a plugin was named `@heroku-cli/plugin-kafka` you could install it either with `heroku plugins:install @heroku-cli/plugin-kafka` OR `heroku plugins:install kafka` This also allows us to declare which plugins are official.


None of this will impact the current behavior so it should be safe to merge now.

**Comment by raulb** [comment]
@jdxcode thanks for the clarification. 

Just FYI, I brought the version [back to 2.5.1.](6ef45094395cc6f8c14bc6ecc55071d5480ef4ae) since that hadn't been released. Noticed also there was a tag already created before merging this in. I deleted it, but now I'm still getting this from GitHub:

```
? Will bump from 2.5.1 to 2.5.2. Continue? Yes
 ❯ Prerequisite check
   ✔ Ping npm registry
   ✔ Verify user is authenticated
   ✔ Check git remote
   ✔ Validate version
   ✔ Check for pre-release version
   ✔ Check npm version
   ✖ Check git tag existence
     → Git tag `v2.5.2` already exists.
   Git
   Cleanup
   Installing dependencies using Yarn
   Running tests
   Publishing package using Yarn
   Pushing tags

✖ Git tag `v2.5.2` already exists.
```

**Comment by raulb** [comment]
Deleting the remote tag from the CLI worked. However, I'm getting this when releasing it:

```
› np

Publish a new version of @heroku-cli/plugin-pipelines (current: 2.5.1)

? Select semver increment or specify new version patch 	2.5.2

Commits:
- Update yarn.lock  a726fd4
- Bring version back to 2.5.1.  6ef4509
- Update CHANGELOG.md  48cbb38
- Merge pull request #85 from heroku/oclif  0c5f913
- Update changelog  bac9e0b
- v2.5.2  ff4912b
- oclifify  8188dcd

? Will bump from 2.5.1 to 2.5.2. Continue? Yes
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies using Yarn
 ✔ Running tests
 ✖ Publishing package using Yarn
   → info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
   Pushing tags

✖ Command failed: yarn publish --new-version 2.5.2
/bin/sh: oclif-dev: command not found
error Command failed with exit code 127.

yarn publish v1.3.2
[1/4] Bumping version...
info Current version: 2.5.1
info New version: 2.5.2
[2/4] Logging in...
[3/4] Publishing...
$ oclif-dev manifest
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
```

**Pull request merged**
