### PR TITLE
switch to got

### PR DESCRIPTION
**Pull request by dickeyxxx**
in reference to https://github.com/heroku/heroku-pipelines/commit/db017d15b77c440b22c5b4fab304da326b33ce07#commitcomment-16109187

@krummi I might need your help with this (see failing test). Code seems right to me, but for some reason one of the expectation isn't getting hit. Any ideas?

Great job on the testing btw! This plugin probably has the most comprehensive test suite!

### CODE REVIEW

**Comment by krummi** [comment]
Seem right to me as well but haven't been able to track down the problem, to be continued in the morning ...

**Comment by krummi** [comment]
@dickeyxxx: Sorry I wasn't able to a look at this earlier but I found that there were some HTTP requests that were being made that were not "nocked" out in the tests. This meant that errors were being thrown that the "requests" handled properly but "got" did not. This patch should fix it:

```javascript
diff --git a/test/commands/pipelines/diff.js b/test/commands/pipelines/diff.js
index d928c87..fb61d0b 100644
--- a/test/commands/pipelines/diff.js
+++ b/test/commands/pipelines/diff.js
@@ -107,21 +107,26 @@ describe('pipelines:diff', function () {
     beforeEach(function () {
       mockPipelineCoupling();
       mockApps();
+      nock(kolkrabbiApi)
+        .get(`/apps/${downstreamApp1.id}/github`)
+        .reply(200, downstreamApp1Github)
+        .get(`/apps/${downstreamApp2.id}/github`)
+        .reply(200, downstreamApp2Github);
     });

-    it('should return an error if the app is not connected to GitHub', function () {
+    it('should return an error if the target app is not connected to GitHub', function () {
       const req = nock(kolkrabbiApi)
         .get(`/apps/${targetApp.id}/github`)
         .reply(404, { message: 'Not found.' });

-        return cmd.run({ app: targetApp.name })
-        .then(function () {
-          req.done();
-          expect(cli.stderr).to.contain('connected to GitHub');
-        });
+      return cmd.run({ app: targetApp.name })
+      .then(function () {
+        req.done();
+        expect(cli.stderr).to.contain('connected to GitHub');
+      });
     });

-    it('should return an error if the app has no release', function () {
+    it('should return an error if the target app has no release', function () {
       nock(kolkrabbiApi)
         .get(`/apps/${targetApp.id}/github`)
         .reply(200, targetGithubApp);
```
(I don't have a commit bit so you're gonna have to apply this.)

**Comment by dickeyxxx** [comment]
thanks for the help!

**Comment by krummi** [comment]
np! :+1:

**Comment by dickeyxxx** [comment]
thanks again for the help with this @krummi, it shrunk the `node_modules` directory from 49mb to 22mb!

**Comment by krummi** [comment]
Wow fantastic and aboslute no problem! :D

**Comment by gudmundur** [comment]
Thanks @krummi!

**Pull request merged**
