### PR TITLE
Upgrade heroku-cli-util & add co.wrap to commands

### PR DESCRIPTION
**Pull request by ransombriggs**

### CODE REVIEW

**Comment by ransombriggs** [comment]
Needed to bump heroku-cli-util to get a fix in, but heroku-cli-util no longer wraps commands in co.wrap so I had to add manually.  All the tests pass, just wanted a review in case I missed an untested command or something.

**Comment by ransombriggs** [comment]
@dickeyxxx or @aa or @gudmundur could one of you review this?  (pulled from the list of contributors)

**Comment by aa** [comment]
LGTM 👍

**Comment by dickeyxxx** [comment]
again, sorry about this change, I should've documented/communicated this as well as checked more plugins to make sure they would continue to work.

The biggest reason for me doing this was to drop a dependency and shorten the stack traces.

**Pull request merged**
